@startuml diagram-network

!define AzurePuml https://raw.githubusercontent.com/travisnielsen/Azure-PlantUML/release/3-0/dist
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/General/ManagementPortal.puml
!includeurl AzurePuml/Compute/KubernetesServices.puml
!includeurl AzurePuml/Compute/AppServiceEnvironments.puml
!includeurl AzurePuml/Compute/FunctionApps.puml
!includeurl AzurePuml/Compute/VirtualMachine.puml
!includeurl AzurePuml/Databases/SQLDataWarehouses.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml
!includeurl AzurePuml/Identity/Users.puml
!includeurl AzurePuml/ManagementGovernance/NetworkWatcher.puml
!includeurl AzurePuml/Networking/AzureFirewall.puml
!includeurl AzurePuml/Networking/Bastion.puml
!includeurl AzurePuml/Networking/NetworkSecurityGroups.puml
!includeurl AzurePuml/Networking/PrivateLink.puml
!includeurl AzurePuml/Networking/PrivateLinkService.puml
!includeurl AzurePuml/Networking/VirtualNetworks.puml
!includeurl AzurePuml/Analytics/AzureDatabricks.puml
!includeurl AzurePuml/Analytics/DataFactory.puml
!includeurl AzurePuml/Analytics/AzureSynapseAnalytics.puml
!includeurl AzurePuml/Storage/StorageAccounts.puml
!includeurl AzurePuml/Security/KeyVault.puml
!includeurl AzurePuml/Identity/AzureActiveDirectory.puml

LAYOUT_LEFT_RIGHT

' Color theme: http://simianuprising.com/wp-content/uploads/2012/08/solarized-reference-horizontal.png

' TITLE: Overview

skinparam BackgroundColor #002b36
skinparam TitleFontColor #eee8d5
skinparam TitleFontSize 35

skinparam Rectangle {
    BackgroundColor<<subnet>> #93a1a1
    ' BorderColor<<networkAcls>> #7C0A02
    'StereotypeFontColor #eee8d5
}

skinparam rectangle<<container>> {
    BackgroundColor<<VirtualNetworks>> #073642
    FontColor<<VirtualNetworks>> #eee8d5

    BackgroundColor<<Users>> #eee8d5
    BackgroundColor<<AzureActiveDirectory>> #eee8d5
    BackgroundColor<<ManagementPortal>> #eee8d5
    BackgroundColor<<AzureFirewall>> #eee8d5

    BackgroundColor<<Bastion>> #eee8d5
    BackgroundColor<<VirtualMachine>> #eee8d5
    BackgroundColor<<PrivateLink>> #eee8d5
    BackgroundColor<<DataFactory>> #eee8d5
    BackgroundColor<<StorageAccounts>> #eee8d5
    BackgroundColor<<SQLDataWarehouses>> #eee8d5
    BackgroundColor<<FunctionApps>> #eee8d5

    BackgroundColor<<NetworkWatcher>> #eee8d5
    BackgroundColor<<NetworkSecurityGroups>> #eee8d5
    BackgroundColor<<udr>> #002b36
}

skinparam package<<container>> {
    StereotypeFontColor<<VirtualNetworks>> #eee8d5
}


VirtualNetworks(vnetHub, "vnet-hub", "10.10.0.0/20") {
    Rectangle "azfw" <<subnet>> as subFirewall #line.dotted {
        AzureFirewall(azfw, "Hub Firewall", "", "Deny egress (default)")
    }

    Rectangle "bastion" <<subnet>> as subBastion #line.dotted {
        Bastion(bastion, "Bastion", "", "SSH / RDP Proxy")
    }
}

VirtualNetworks(vnetSpoke, "vnet-spoke", "10.20.0.0/20") {


    Rectangle "util" <<subnet>> as subUtil #line.dotted {
        VirtualMachine(vm, "Utility Servers", "", "Allow SSH / RDP from Bastion subnet")
        Container(udr1, "User Defined Route", "Force egress to hub", "0.0.0.0 to AZFW")
    }

    Rectangle "az-svcs" <<subnet>> as subPrivateLinks #line.dotted {
        PrivateLink(azsvcLink, "Azure Services", "", "Inbound connections")
    }

    Rectangle "func-integration" <<subnet>> as subFuncInt #line.dotted {
        Container(udr2, "User Defined Route", "Force egress to hub", "0.0.0.0 to AZFW")
    }
}

Users(users, "Admins", "", "")
AzureActiveDirectory(aad, "Corprate tenant", "", "MFA\nConditional Access")
ManagementPortal(portal, "Azure Portal", "", "Connect to utility servers")
users -[#b48900]-> aad: "<color:#b48900>Authentication"
users -[#d33682]-> portal
portal -[#d33682]-> bastion: "<color:#d33682>https"
bastion -[#d33682]-> vm: "<color:#d33682>RDP/SSH"

vnetHub -[#268bd2]-- vnetSpoke: "<color:#268bd2><size:18>VNET\n<color:#268bd2><size:18>Peering"

NetworkWatcher(netWatcher, "Traffic Analytics", "", "")
NetworkSecurityGroups(nsgs, "Traffic Segmentation", "1 per subnet", "Deny outbound Internet\nExplicit inbound allow")

netWatcher <-[#268bd2]- nsgs: "<color:#268bd2>Flow logs"
nsgs -[#268bd2]-> subBastion: "<color:#268bd2>nsg-bastion"
nsgs -[#268bd2]-> subUtil: "<color:#268bd2>nsg-util"
nsgs -[#268bd2]-> subPrivateLinks: "<color:#268bd2>nsg-services"
nsgs -[#268bd2]-> subFuncInt: "<color:#268bd2>nsg-integration"

StorageAccounts(adls, "Data Lake", "Standard SKU", "Source data")
azsvcLink -[#859900]-> adls: "<color:#859900>Private Link"

SQLDataWarehouses(sqldw, "SQL Synapse", "", "Enriched data")
azsvcLink -[#859900]-> sqldw: "<color:#859900>Private Link"

FunctionApps(functions, "Functions", "Premium Plan", "Private storage account for service (preview)")
azsvcLink -[#859900]-> functions: "<color:#859900>Private Link"
subFuncInt <-[#2aa198]- functions: "<color:#2aa198>VNET Integration (outbound)"

DataFactory(datafactory, "Data Processing", "Managed Virtual Network", "ETL jobs")
azsvcLink <-[#2aa198]- datafactory: "<color:#2aa198>data access"

@end